# Generated by Django 6.0.6 on 2026-06-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='identifier',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='priceUnitaire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prixttc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='totalMontant',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='designationProduct',
            field=models.CharField(default='ddd', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nameProduct',
            field=models.CharField(default='identifier', max_length=200, null=True),
        ),
    ]
