# Generated by Django 6.0.6 on 2026-06-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('mark', '0001_initial'),
        ('product', '0002_product_identifier_product_priceunitaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categorie.categorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='mark.mark'),
        ),
    ]
