# Generated by Django 6.0.6 on 2026-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodeVol', models.IntegerField()),
                ('contact', models.CharField(max_length=200)),
                ('departDate', models.DateField()),
                ('nombrePassage', models.IntegerField()),
                ('prixTicket', models.FloatField()),
            ],
        ),
    ]
